# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "hashicorp/bionic64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # B
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # A
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

  #BASE_IP = "172.17.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 1
  end
  
  config.vm.define "multi-server-dev" do |controller|

    controller.vm.provider "virtualbox" do |vb, override|

      #override.vm.network "private_network", ip: "#{BASE_IP}.11"
      #override.vm.hostname = "multi-server-dev"
      #vb.name = "multi-server-dev"
    
      controller.vm.provision "basic", type: "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y tree
        sudo apt-get install -y unzip
        sudo apt-get install -y git 
        sudo apt-get install -y ruby-full
      SHELL

      controller.vm.provision "python", type: "shell", inline: <<-SHELL
        python --version
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
        sudo update-alternatives --set python /usr/bin/python3
        python --version
      SHELL

      controller.vm.provision "ansible-install", type: "ansible_local" do |ansible|
        ansible.playbook = "list.yml"
        ansible.become = true
        ansible.limit = "all"
        ansible.inventory_path = "inventory.txt"
      end

      controller.vm.provision "ansible-config", type: "shell", inline: <<-SHELL
        /vagrant/ansible-cfg.sh /etc/ansible/ansible.cfg /vagrant/inventory.txt
      SHELL

      controller.vm.provision "test-pwd", type: "shell", run: "never", inline: <<-SHELL
        pwd
      SHELL

    end

  end

end
